#ifndef __NCIV_H__
#define __NCIV_H__

extern void GPIO000_Handler(void);
extern void GPIO001_Handler(void);
extern void GPIO002_Handler(void);
extern void GPIO003_Handler(void);
extern void GPIO004_Handler(void);
extern void GPIO005_Handler(void);
extern void GPIO006_Handler(void);
extern void GPIO007_Handler(void);
extern void GPIO008_Handler(void);
extern void GPIO009_Handler(void);
extern void GPIO010_Handler(void);
extern void GPIO011_Handler(void);
extern void GPIO012_Handler(void);
extern void GPIO013_Handler(void);
extern void GPIO014_Handler(void);
extern void GPIO015_Handler(void);
extern void GPIO016_Handler(void);
extern void GPIO017_Handler(void);
extern void GPIO018_Handler(void);
extern void GPIO019_Handler(void);
extern void GPIO020_Handler(void);
extern void GPIO021_Handler(void);
extern void GPIO022_Handler(void);
extern void GPIO023_Handler(void);
extern void GPIO024_Handler(void);
extern void GPIO025_Handler(void);
extern void GPIO026_Handler(void);
extern void GPIO027_Handler(void);
extern void GPIO028_Handler(void);
extern void GPIO029_Handler(void);
extern void GPIO030_Handler(void);
extern void GPIO031_Handler(void);
extern void GPIO032_Handler(void);
extern void GPIO033_Handler(void);
extern void GPIO034_Handler(void);
extern void GPIO035_Handler(void);
extern void GPIO036_Handler(void);
extern void GPIO037_Handler(void);
extern void GPIO038_Handler(void);
extern void GPIO039_Handler(void);
extern void GPIO040_Handler(void);
extern void GPIO041_Handler(void);
extern void GPIO042_Handler(void);
extern void GPIO043_Handler(void);
extern void GPIO044_Handler(void);
extern void GPIO045_Handler(void);
extern void GPIO046_Handler(void);
extern void GPIO047_Handler(void);
extern void GPIO048_Handler(void);
extern void GPIO049_Handler(void);
extern void GPIO050_Handler(void);
extern void GPIO051_Handler(void);
extern void GPIO052_Handler(void);
extern void GPIO053_Handler(void);
extern void GPIO054_Handler(void);
extern void GPIO055_Handler(void);
extern void GPIO056_Handler(void);
extern void GPIO057_Handler(void);
extern void GPIO058_Handler(void);
extern void GPIO059_Handler(void);
extern void GPIO060_Handler(void);
extern void GPIO061_Handler(void);
extern void GPIO062_Handler(void);
extern void GPIO063_Handler(void);
extern void GPIO064_Handler(void);
extern void GPIO065_Handler(void);
extern void GPIO066_Handler(void);
extern void GPIO067_Handler(void);
extern void GPIO068_Handler(void);
extern void GPIO069_Handler(void);
extern void GPIO070_Handler(void);
extern void GPIO071_Handler(void);
extern void GPIO072_Handler(void);
extern void GPIO073_Handler(void);
extern void GPIO074_Handler(void);
extern void GPIO075_Handler(void);
extern void GPIO076_Handler(void);
extern void GPIO077_Handler(void);
extern void GPIO078_Handler(void);
extern void GPIO079_Handler(void);
extern void GPIO080_Handler(void);
extern void GPIO081_Handler(void);
extern void GPIO082_Handler(void);
extern void GPIO083_Handler(void);
extern void GPIO084_Handler(void);
extern void GPIO085_Handler(void);
extern void GPIO086_Handler(void);
extern void GPIO087_Handler(void);
extern void GPIO088_Handler(void);
extern void GPIO089_Handler(void);
extern void GPIO090_Handler(void);
extern void GPIO091_Handler(void);
extern void GPIO092_Handler(void);
extern void GPIO093_Handler(void);
extern void GPIO094_Handler(void);
extern void GPIO095_Handler(void);
extern void GPIO096_Handler(void);
extern void GPIO097_Handler(void);
extern void GPIO098_Handler(void);
extern void GPIO099_Handler(void);
extern void GPIO100_Handler(void);
extern void GPIO101_Handler(void);
extern void GPIO102_Handler(void);
extern void GPIO103_Handler(void);
extern void GPIO104_Handler(void);
extern void GPIO105_Handler(void);
extern void GPIO106_Handler(void);
extern void GPIO107_Handler(void);
extern void GPIO108_Handler(void);
extern void GPIO109_Handler(void);
extern void GPIO110_Handler(void);
extern void GPIO111_Handler(void);
extern void GPIO112_Handler(void);
extern void GPIO113_Handler(void);
extern void GPIO114_Handler(void);
extern void GPIO115_Handler(void);
extern void GPIO116_Handler(void);
extern void GPIO117_Handler(void);
extern void GPIO118_Handler(void);
extern void GPIO119_Handler(void);
extern void GPIO120_Handler(void);
extern void GPIO121_Handler(void);
extern void GPIO122_Handler(void);
extern void GPIO123_Handler(void);
extern void GPIO124_Handler(void);
extern void GPIO125_Handler(void);
extern void GPIO126_Handler(void);
extern void GPIO127_Handler(void);
extern void GPIO128_Handler(void);
extern void GPIO129_Handler(void);
extern void GPIO130_Handler(void);
extern void GPIO131_Handler(void);
extern void ERST_Handler(void);
extern void EPRCH_Handler(void);
extern void EVCHIDX61_Handler(void);
extern void EVCHIDX51_Handler(void);
extern void EVCHIDX4A_Handler(void);
extern void EVCHIDX47_Handler(void);
extern void EVCHIDX44_Handler(void);
extern void EVCHIDX43_Handler(void);
extern void EVCHIDX42_Handler(void);
extern void EVCHIDX41_Handler(void);
extern void EVCHIDX7_Handler(void);
extern void EVCHIDX3_Handler(void);
extern void EVCHIDX2_Handler(void);
extern void EVCH_Handler(void);
extern void EOCHTX_Handler(void);
extern void EOCHRX_Handler(void);
extern void EOCHCFGEN_Handler(void);
extern void EFSAFSTR_Handler(void);
extern void EFSAFSERASE_Handler(void);
extern void EFMAFSTR_Handler(void);
extern void EFCHCHG_Handler(void);
extern void KBC_IB_Handler(void);
extern void KBC_OB_Handler(void);
extern void ACPI_IB_Handler(void);
extern void ACPI_OB_Handler(void);
extern void PMPORT0_IB_Handler(void);
extern void PMPORT0_OB_Handler(void);
extern void PMPORT1_IB_Handler(void);
extern void PMPORT1_OB_Handler(void);
extern void PMPORT2_IB_Handler(void);
extern void PMPORT2_OB_Handler(void);
extern void PMPORT3_IB_Handler(void);
extern void PMPORT3_OB_Handler(void);
extern void PORT80_Handler(void);
extern void PORT81_Handler(void);
extern void PECI_Handler(void);
extern void EFSAFOP2_Handler(void);
extern void SPIC_Handler(void);
extern void HSPI_Handler(void);
extern void I2C0_Handler(void);
extern void I2C1_Handler(void);
extern void I2C2_Handler(void);
extern void I2C3_Handler(void);
extern void I2C4_Handler(void);
extern void I2C5_Handler(void);
extern void I2C6_Handler(void);
extern void I2C7_Handler(void);
extern void PS2_Handler(void);
extern void UART_Handler(void);
extern void TACHO0_Handler(void);
extern void TACHO1_Handler(void);
extern void TACHO2_Handler(void);
extern void TACHO3_Handler(void);
extern void TMR0_Handler(void);
extern void TMR1_Handler(void);
extern void TMR2_Handler(void);
extern void TMR3_Handler(void);
extern void TMR4_Handler(void);
extern void TMR5_Handler(void);
extern void SLWTMR0_Handler(void);
extern void SLWTMR1_Handler(void);
extern void RTMR_Handler(void);
extern void RTC_Handler(void);
extern void I3C0_Handler(void);
extern void I3C1_Handler(void);
extern void PWRBTN_Handler(void);
extern void WDT_Handler(void);
extern void KBM_Handler(void);
extern void MSPI_Handler(void);
extern void EMI0_Handler(void);
extern void EMI1_Handler(void);
extern void EMI2_Handler(void);
extern void EMI3_Handler(void);
extern void EMI4_Handler(void);
extern void EMI5_Handler(void);
extern void EMI6_Handler(void);
extern void EMI7_Handler(void);
extern void MBX_Handler(void);
extern void ADC_Handler(void);
extern void DMA_Handler(void);
extern void SHA2_Handler(void);
extern void SHA3_Handler(void);
extern void AES_Handler(void);
extern void PKE_Handler(void);
extern void PUFOTP_Handler(void);

void GPIO000_EnableIRQ(void);
void GPIO001_EnableIRQ(void);
void GPIO002_EnableIRQ(void);
void GPIO003_EnableIRQ(void);
void GPIO004_EnableIRQ(void);
void GPIO005_EnableIRQ(void);
void GPIO006_EnableIRQ(void);
void GPIO007_EnableIRQ(void);
void GPIO008_EnableIRQ(void);
void GPIO009_EnableIRQ(void);
void GPIO010_EnableIRQ(void);
void GPIO011_EnableIRQ(void);
void GPIO012_EnableIRQ(void);
void GPIO013_EnableIRQ(void);
void GPIO014_EnableIRQ(void);
void GPIO015_EnableIRQ(void);
void GPIO016_EnableIRQ(void);
void GPIO017_EnableIRQ(void);
void GPIO018_EnableIRQ(void);
void GPIO019_EnableIRQ(void);
void GPIO020_EnableIRQ(void);
void GPIO021_EnableIRQ(void);
void GPIO022_EnableIRQ(void);
void GPIO023_EnableIRQ(void);
void GPIO024_EnableIRQ(void);
void GPIO025_EnableIRQ(void);
void GPIO026_EnableIRQ(void);
void GPIO027_EnableIRQ(void);
void GPIO028_EnableIRQ(void);
void GPIO029_EnableIRQ(void);
void GPIO030_EnableIRQ(void);
void GPIO031_EnableIRQ(void);
void GPIO032_EnableIRQ(void);
void GPIO033_EnableIRQ(void);
void GPIO034_EnableIRQ(void);
void GPIO035_EnableIRQ(void);
void GPIO036_EnableIRQ(void);
void GPIO037_EnableIRQ(void);
void GPIO038_EnableIRQ(void);
void GPIO039_EnableIRQ(void);
void GPIO040_EnableIRQ(void);
void GPIO041_EnableIRQ(void);
void GPIO042_EnableIRQ(void);
void GPIO043_EnableIRQ(void);
void GPIO044_EnableIRQ(void);
void GPIO045_EnableIRQ(void);
void GPIO046_EnableIRQ(void);
void GPIO047_EnableIRQ(void);
void GPIO048_EnableIRQ(void);
void GPIO049_EnableIRQ(void);
void GPIO050_EnableIRQ(void);
void GPIO051_EnableIRQ(void);
void GPIO052_EnableIRQ(void);
void GPIO053_EnableIRQ(void);
void GPIO054_EnableIRQ(void);
void GPIO055_EnableIRQ(void);
void GPIO056_EnableIRQ(void);
void GPIO057_EnableIRQ(void);
void GPIO058_EnableIRQ(void);
void GPIO059_EnableIRQ(void);
void GPIO060_EnableIRQ(void);
void GPIO061_EnableIRQ(void);
void GPIO062_EnableIRQ(void);
void GPIO063_EnableIRQ(void);
void GPIO064_EnableIRQ(void);
void GPIO065_EnableIRQ(void);
void GPIO066_EnableIRQ(void);
void GPIO067_EnableIRQ(void);
void GPIO068_EnableIRQ(void);
void GPIO069_EnableIRQ(void);
void GPIO070_EnableIRQ(void);
void GPIO071_EnableIRQ(void);
void GPIO072_EnableIRQ(void);
void GPIO073_EnableIRQ(void);
void GPIO074_EnableIRQ(void);
void GPIO075_EnableIRQ(void);
void GPIO076_EnableIRQ(void);
void GPIO077_EnableIRQ(void);
void GPIO078_EnableIRQ(void);
void GPIO079_EnableIRQ(void);
void GPIO080_EnableIRQ(void);
void GPIO081_EnableIRQ(void);
void GPIO082_EnableIRQ(void);
void GPIO083_EnableIRQ(void);
void GPIO084_EnableIRQ(void);
void GPIO085_EnableIRQ(void);
void GPIO086_EnableIRQ(void);
void GPIO087_EnableIRQ(void);
void GPIO088_EnableIRQ(void);
void GPIO089_EnableIRQ(void);
void GPIO090_EnableIRQ(void);
void GPIO091_EnableIRQ(void);
void GPIO092_EnableIRQ(void);
void GPIO093_EnableIRQ(void);
void GPIO094_EnableIRQ(void);
void GPIO095_EnableIRQ(void);
void GPIO096_EnableIRQ(void);
void GPIO097_EnableIRQ(void);
void GPIO098_EnableIRQ(void);
void GPIO099_EnableIRQ(void);
void GPIO100_EnableIRQ(void);
void GPIO101_EnableIRQ(void);
void GPIO102_EnableIRQ(void);
void GPIO103_EnableIRQ(void);
void GPIO104_EnableIRQ(void);
void GPIO105_EnableIRQ(void);
void GPIO106_EnableIRQ(void);
void GPIO107_EnableIRQ(void);
void GPIO108_EnableIRQ(void);
void GPIO109_EnableIRQ(void);
void GPIO110_EnableIRQ(void);
void GPIO111_EnableIRQ(void);
void GPIO112_EnableIRQ(void);
void GPIO113_EnableIRQ(void);
void GPIO114_EnableIRQ(void);
void GPIO115_EnableIRQ(void);
void GPIO116_EnableIRQ(void);
void GPIO117_EnableIRQ(void);
void GPIO118_EnableIRQ(void);
void GPIO119_EnableIRQ(void);
void GPIO120_EnableIRQ(void);
void GPIO121_EnableIRQ(void);
void GPIO122_EnableIRQ(void);
void GPIO123_EnableIRQ(void);
void GPIO124_EnableIRQ(void);
void GPIO125_EnableIRQ(void);
void GPIO126_EnableIRQ(void);
void GPIO127_EnableIRQ(void);
void GPIO128_EnableIRQ(void);
void GPIO129_EnableIRQ(void);
void GPIO130_EnableIRQ(void);
void GPIO131_EnableIRQ(void);
void ERST_EnableIRQ(void);
void EPRCH_EnableIRQ(void);
void EVCHIDX61_EnableIRQ(void);
void EVCHIDX51_EnableIRQ(void);
void EVCHIDX4A_EnableIRQ(void);
void EVCHIDX47_EnableIRQ(void);
void EVCHIDX44_EnableIRQ(void);
void EVCHIDX43_EnableIRQ(void);
void EVCHIDX42_EnableIRQ(void);
void EVCHIDX41_EnableIRQ(void);
void EVCHIDX7_EnableIRQ(void);
void EVCHIDX3_EnableIRQ(void);
void EVCHIDX2_EnableIRQ(void);
void EVCH_EnableIRQ(void);
void EOCHTX_EnableIRQ(void);
void EOCHRX_EnableIRQ(void);
void EOCHCFGEN_EnableIRQ(void);
void EFSAFSTR_EnableIRQ(void);
void EFSAFSERASE_EnableIRQ(void);
void EFMAFSTR_EnableIRQ(void);
void EFCHCHG_EnableIRQ(void);
void KBC_IB_EnableIRQ(void);
void KBC_OB_EnableIRQ(void);
void ACPI_IB_EnableIRQ(void);
void ACPI_OB_EnableIRQ(void);
void PMPORT0_IB_EnableIRQ(void);
void PMPORT0_OB_EnableIRQ(void);
void PMPORT1_IB_EnableIRQ(void);
void PMPORT1_OB_EnableIRQ(void);
void PMPORT2_IB_EnableIRQ(void);
void PMPORT2_OB_EnableIRQ(void);
void PMPORT3_IB_EnableIRQ(void);
void PMPORT3_OB_EnableIRQ(void);
void PORT80_EnableIRQ(void);
void PORT81_EnableIRQ(void);
void PECI_EnableIRQ(void);
void EFSAFOP2_EnableIRQ(void);
void SPIC_EnableIRQ(void);
void HSPI_EnableIRQ(void);
void I2C0_EnableIRQ(void);
void I2C1_EnableIRQ(void);
void I2C2_EnableIRQ(void);
void I2C3_EnableIRQ(void);
void I2C4_EnableIRQ(void);
void I2C5_EnableIRQ(void);
void I2C6_EnableIRQ(void);
void I2C7_EnableIRQ(void);
void PS2_EnableIRQ(void);
void UART_EnableIRQ(void);
void TACHO0_EnableIRQ(void);
void TACHO1_EnableIRQ(void);
void TACHO2_EnableIRQ(void);
void TACHO3_EnableIRQ(void);
void TMR0_EnableIRQ(void);
void TMR1_EnableIRQ(void);
void TMR2_EnableIRQ(void);
void TMR3_EnableIRQ(void);
void TMR4_EnableIRQ(void);
void TMR5_EnableIRQ(void);
void SLWTMR0_EnableIRQ(void);
void SLWTMR1_EnableIRQ(void);
void RTMR_EnableIRQ(void);
void PWRBTN_EnableIRQ(void);
void WDT_EnableIRQ(void);
void KBM_EnableIRQ(void);
void MSPI_EnableIRQ(void);
void EMI0_EnableIRQ(void);
void EMI1_EnableIRQ(void);
void EMI2_EnableIRQ(void);
void EMI3_EnableIRQ(void);
void EMI4_EnableIRQ(void);
void EMI5_EnableIRQ(void);
void EMI6_EnableIRQ(void);
void EMI7_EnableIRQ(void);
void MBX_EnableIRQ(void);
void ADC_EnableIRQ(void);
void DMA_EnableIRQ(void);
void SHA2_EnableIRQ(void);
void SHA3_EnableIRQ(void);
void AES_EnableIRQ(void);
void PKE_EnableIRQ(void);
void PUFOTP_EnableIRQ(void);

void GPIO000_DisableIRQ(void);
void GPIO001_DisableIRQ(void);
void GPIO002_DisableIRQ(void);
void GPIO003_DisableIRQ(void);
void GPIO004_DisableIRQ(void);
void GPIO005_DisableIRQ(void);
void GPIO006_DisableIRQ(void);
void GPIO007_DisableIRQ(void);
void GPIO008_DisableIRQ(void);
void GPIO009_DisableIRQ(void);
void GPIO010_DisableIRQ(void);
void GPIO011_DisableIRQ(void);
void GPIO012_DisableIRQ(void);
void GPIO013_DisableIRQ(void);
void GPIO014_DisableIRQ(void);
void GPIO015_DisableIRQ(void);
void GPIO016_DisableIRQ(void);
void GPIO017_DisableIRQ(void);
void GPIO018_DisableIRQ(void);
void GPIO019_DisableIRQ(void);
void GPIO020_DisableIRQ(void);
void GPIO021_DisableIRQ(void);
void GPIO022_DisableIRQ(void);
void GPIO023_DisableIRQ(void);
void GPIO024_DisableIRQ(void);
void GPIO025_DisableIRQ(void);
void GPIO026_DisableIRQ(void);
void GPIO027_DisableIRQ(void);
void GPIO028_DisableIRQ(void);
void GPIO029_DisableIRQ(void);
void GPIO030_DisableIRQ(void);
void GPIO031_DisableIRQ(void);
void GPIO032_DisableIRQ(void);
void GPIO033_DisableIRQ(void);
void GPIO034_DisableIRQ(void);
void GPIO035_DisableIRQ(void);
void GPIO036_DisableIRQ(void);
void GPIO037_DisableIRQ(void);
void GPIO038_DisableIRQ(void);
void GPIO039_DisableIRQ(void);
void GPIO040_DisableIRQ(void);
void GPIO041_DisableIRQ(void);
void GPIO042_DisableIRQ(void);
void GPIO043_DisableIRQ(void);
void GPIO044_DisableIRQ(void);
void GPIO045_DisableIRQ(void);
void GPIO046_DisableIRQ(void);
void GPIO047_DisableIRQ(void);
void GPIO048_DisableIRQ(void);
void GPIO049_DisableIRQ(void);
void GPIO050_DisableIRQ(void);
void GPIO051_DisableIRQ(void);
void GPIO052_DisableIRQ(void);
void GPIO053_DisableIRQ(void);
void GPIO054_DisableIRQ(void);
void GPIO055_DisableIRQ(void);
void GPIO056_DisableIRQ(void);
void GPIO057_DisableIRQ(void);
void GPIO058_DisableIRQ(void);
void GPIO059_DisableIRQ(void);
void GPIO060_DisableIRQ(void);
void GPIO061_DisableIRQ(void);
void GPIO062_DisableIRQ(void);
void GPIO063_DisableIRQ(void);
void GPIO064_DisableIRQ(void);
void GPIO065_DisableIRQ(void);
void GPIO066_DisableIRQ(void);
void GPIO067_DisableIRQ(void);
void GPIO068_DisableIRQ(void);
void GPIO069_DisableIRQ(void);
void GPIO070_DisableIRQ(void);
void GPIO071_DisableIRQ(void);
void GPIO072_DisableIRQ(void);
void GPIO073_DisableIRQ(void);
void GPIO074_DisableIRQ(void);
void GPIO075_DisableIRQ(void);
void GPIO076_DisableIRQ(void);
void GPIO077_DisableIRQ(void);
void GPIO078_DisableIRQ(void);
void GPIO079_DisableIRQ(void);
void GPIO080_DisableIRQ(void);
void GPIO081_DisableIRQ(void);
void GPIO082_DisableIRQ(void);
void GPIO083_DisableIRQ(void);
void GPIO084_DisableIRQ(void);
void GPIO085_DisableIRQ(void);
void GPIO086_DisableIRQ(void);
void GPIO087_DisableIRQ(void);
void GPIO088_DisableIRQ(void);
void GPIO089_DisableIRQ(void);
void GPIO090_DisableIRQ(void);
void GPIO091_DisableIRQ(void);
void GPIO092_DisableIRQ(void);
void GPIO093_DisableIRQ(void);
void GPIO094_DisableIRQ(void);
void GPIO095_DisableIRQ(void);
void GPIO096_DisableIRQ(void);
void GPIO097_DisableIRQ(void);
void GPIO098_DisableIRQ(void);
void GPIO099_DisableIRQ(void);
void GPIO100_DisableIRQ(void);
void GPIO101_DisableIRQ(void);
void GPIO102_DisableIRQ(void);
void GPIO103_DisableIRQ(void);
void GPIO104_DisableIRQ(void);
void GPIO105_DisableIRQ(void);
void GPIO106_DisableIRQ(void);
void GPIO107_DisableIRQ(void);
void GPIO108_DisableIRQ(void);
void GPIO109_DisableIRQ(void);
void GPIO110_DisableIRQ(void);
void GPIO111_DisableIRQ(void);
void GPIO112_DisableIRQ(void);
void GPIO113_DisableIRQ(void);
void GPIO114_DisableIRQ(void);
void GPIO115_DisableIRQ(void);
void GPIO116_DisableIRQ(void);
void GPIO117_DisableIRQ(void);
void GPIO118_DisableIRQ(void);
void GPIO119_DisableIRQ(void);
void GPIO120_DisableIRQ(void);
void GPIO121_DisableIRQ(void);
void GPIO122_DisableIRQ(void);
void GPIO123_DisableIRQ(void);
void GPIO124_DisableIRQ(void);
void GPIO125_DisableIRQ(void);
void GPIO126_DisableIRQ(void);
void GPIO127_DisableIRQ(void);
void GPIO128_DisableIRQ(void);
void GPIO129_DisableIRQ(void);
void GPIO130_DisableIRQ(void);
void GPIO131_DisableIRQ(void);
void ERST_DisableIRQ(void);
void EPRCH_DisableIRQ(void);
void EVCHIDX61_DisableIRQ(void);
void EVCHIDX51_DisableIRQ(void);
void EVCHIDX4A_DisableIRQ(void);
void EVCHIDX47_DisableIRQ(void);
void EVCHIDX44_DisableIRQ(void);
void EVCHIDX43_DisableIRQ(void);
void EVCHIDX42_DisableIRQ(void);
void EVCHIDX41_DisableIRQ(void);
void EVCHIDX7_DisableIRQ(void);
void EVCHIDX3_DisableIRQ(void);
void EVCHIDX2_DisableIRQ(void);
void EVCH_DisableIRQ(void);
void EOCHTX_DisableIRQ(void);
void EOCHRX_DisableIRQ(void);
void EOCHCFGEN_DisableIRQ(void);
void EFSAFSTR_DisableIRQ(void);
void EFSAFSERASE_DisableIRQ(void);
void EFMAFSTR_DisableIRQ(void);
void EFCHCHG_DisableIRQ(void);
void KBC_IB_DisableIRQ(void);
void KBC_OB_DisableIRQ(void);
void ACPI_IB_DisableIRQ(void);
void ACPI_OB_DisableIRQ(void);
void PMPORT0_IB_DisableIRQ(void);
void PMPORT0_OB_DisableIRQ(void);
void PMPORT1_IB_DisableIRQ(void);
void PMPORT1_OB_DisableIRQ(void);
void PMPORT2_IB_DisableIRQ(void);
void PMPORT2_OB_DisableIRQ(void);
void PMPORT3_IB_DisableIRQ(void);
void PMPORT3_OB_DisableIRQ(void);
void PORT80_DisableIRQ(void);
void PORT81_DisableIRQ(void);
void PECI_DisableIRQ(void);
void EFSAFOP2_DisableIRQ(void);
void SPIC_DisableIRQ(void);
void HSPI_DisableIRQ(void);
void I2C0_DisableIRQ(void);
void I2C1_DisableIRQ(void);
void I2C2_DisableIRQ(void);
void I2C3_DisableIRQ(void);
void I2C4_DisableIRQ(void);
void I2C5_DisableIRQ(void);
void I2C6_DisableIRQ(void);
void I2C7_DisableIRQ(void);
void PS2_DisableIRQ(void);
void UART_DisableIRQ(void);
void TACHO0_DisableIRQ(void);
void TACHO1_DisableIRQ(void);
void TACHO2_DisableIRQ(void);
void TACHO3_DisableIRQ(void);
void TMR0_DisableIRQ(void);
void TMR1_DisableIRQ(void);
void TMR2_DisableIRQ(void);
void TMR3_DisableIRQ(void);
void TMR4_DisableIRQ(void);
void TMR5_DisableIRQ(void);
void SLWTMR0_DisableIRQ(void);
void SLWTMR1_DisableIRQ(void);
void RTMR_DisableIRQ(void);
void PWRBTN_DisableIRQ(void);
void WDT_DisableIRQ(void);
void KBM_DisableIRQ(void);
void MSPI_DisableIRQ(void);
void EMI0_DisableIRQ(void);
void EMI1_DisableIRQ(void);
void EMI2_DisableIRQ(void);
void EMI3_DisableIRQ(void);
void EMI4_DisableIRQ(void);
void EMI5_DisableIRQ(void);
void EMI6_DisableIRQ(void);
void EMI7_DisableIRQ(void);
void MBX_DisableIRQ(void);
void ADC_DisableIRQ(void);
void DMA_DisableIRQ(void);
void SHA2_DisableIRQ(void);
void SHA3_DisableIRQ(void);
void AES_DisableIRQ(void);
void PKE_DisableIRQ(void);
void PUFOTP_DisableIRQ(void);

#endif  /* __NCIV_H__ */
