set(ARM_RTK_TOOLCHAINS C:/asdk-10.2.0/mingw32/newlib/bin)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_C_COMPILER ${ARM_RTK_TOOLCHAINS}/arm-none-eabi-gcc-10.2.0.exe)
set(CMAKE_CXX_COMPILER ${ARM_RTK_TOOLCHAINS}/arm-none-eabi-g++.exe)
set(CMAKE_ASM_COMPILER ${ARM_RTK_TOOLCHAINS}/arm-none-eabi-gcc-10.2.0.exe)
set(CMAKE_LINKER ${ARM_RTK_TOOLCHAINS}/arm-none-eabi-gcc-ld.exe)
set(CMAKE_AR ${ARM_RTK_TOOLCHAINS}/arm-none-eabi-gcc-ar.exe)
set(CMAKE_OBJCOPY ${ARM_RTK_TOOLCHAINS}/arm-none-eabi-objcopy.exe)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_EXECUTABLE_SUFFIX_C ".elf")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)